// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Notification is an autogenerated mock type for the Notification type
type Notification struct {
	mock.Mock
}

type mockConstructorTestingTNewNotification interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotification creates a new instance of Notification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotification(t mockConstructorTestingTNewNotification) *Notification {
	mock := &Notification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
