// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NotificationTemplateRepository is an autogenerated mock type for the NotificationTemplateRepository type
type NotificationTemplateRepository struct {
	mock.Mock
}

// GetNotificationTemplate provides a mock function with given fields: ctx, ID
func (_m *NotificationTemplateRepository) GetNotificationTemplate(ctx context.Context, ID string) (string, error) {
	ret := _m.Called(ctx, ID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNotificationTemplateRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationTemplateRepository creates a new instance of NotificationTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationTemplateRepository(t mockConstructorTestingTNewNotificationTemplateRepository) *NotificationTemplateRepository {
	mock := &NotificationTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
